version: '3.9'

services:
  # General images
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_SERVICE_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_SERVICE_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data_container:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Custom images
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - ${API_SERVICE_PORT}:${API_SERVICE_PORT}
    environment:
      SETUP_JWT_SECRET: ${API_SERVICE_JWT_SECRET}
      SETUP_PORT: ${API_SERVICE_PORT}
      SETUP_API_PREFIX: ${API_SERVICE_API_PREFIX}
      SETUP_NODE_ENV: ${API_SERVICE_NODE_ENV}
      CORS_WHITELIST: ${API_SERVICE_CORS_WHITELIST}
      MONGO_URI: mongodb://${MONGO_HOST}:${MONGO_PORT}
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongo
    restart: always

volumes:
  mongodb_data_container: